---
title: "Análisis Eco. 2: 5 y 6"
always_allow_html: yes
author:
- Fabiola Cabrera$^1$
- Sebastián Cea$^2$
date: "September 2018"
output:
  beamer_presentation:
    theme: classic
institute:
- Biblio Congreso$^1$
- EII PUCV$^2$
subtitle: Sist. Económicos y Rol del Estado
header-includes:
- \usepackage{pgf,tikz}
- \usetikzlibrary{patterns}
- \usetikzlibrary{arrows}
- \usepackage{pgfplots}
---


# Pendientes Clase 2

-  Variables Reales/Nominales

-  Elasticidad

- FPP: F1.2 y Ejemplo de Política Fiscal 

    - I+D potenciada por CORFO, [Noticia](https://www.emol.com/noticias/Economia/2019/03/01/939627/Gasto-en-ID-alcanzo-036-del-PIB-en-2017-y-registro-su-menor-nivel-en-cinco-anos.html)

----


# Clase 3

- Sist. Económicos N1.5

    -   importancia de competencia en Mcdos

    -   externalidades

- Rol del Estado N5.13 14

    - Marco legal:mínimos, imptos
    
    - Estabilidad macro  Ciclos Económicos N1.15-17
    
    - Redistribución
    
- Lecturas: Dornbush et ali 2.4-9, 17.6


----

- Métricas o factores para medir el tamaño del estado 

    - (Gasto Público/PIB, trabajos sector público, leyes, etc.) 
    - comparando países (China, EEUU)
    
- Variables macroeconómicas. (Crecimiento, Inflación, Desempleo).

- Sector Público y Cuenta corriente

----


# Ciclo Económico N1.15


- Crecimto>Produc>Ingresos>empleo>demanda>costos>$\pi$

- Pol. Fiscal 

    - Expansiva: + gastos ó - imptos (pro crecimiento)
    - Contractiva/Restrictiva: - gasto ó + imptos 
    - Efectos (pro/contra)-cíclico
    - aclaración de las diferencias entre caída del PIB y desaceleración
    - Regla fiscal de superávit estructural N1.17
    - Sistema tributario (esta complejidad de muchos impuestos)
        - [Engel et ali 1999](https://www.sciencedirect.com/science/article/pii/S0304387899000097)
        - [Fairfield and Jorrat 2016](https://doi.org/10.1111/roiw.12196)
    
- Pol. Monetaria

    - Expansiva: $\nabla$i>inv>consumo>producción>empleo
    - Restictiva: i>~(inv>consumo>producción>empleo)
    - Pol. Cambiaria

----


- Crisis N1.15

    - Desaceleración
    - Recesión
    - Manejo expectativas
    
----


# Pendientes Clase 3

- Rol del Estado


----

# Clase 4

- Términos: IPCSAE, IPOM, estímulo monetario, Gini
- Comente: acá en Chile habría una fuerte intervención del Estado debido a que con la tarjeta junaeb podemos comer solo en algunos lugares
    
    
----

# Clase 5

- Producción y conceptos relacionados.
- Crecimiento y conceptos asociados.
- Producción y Crecimiento $\neq$ Desarrollo (mediciones)
- Desarrollo económico y social, inclusivo y sustentable
- Coeficiente de Gini, desarrollo territorial medioambiente
(comparqación entre IDH e indice de competitividad WEF)
- PIB y sus alcances al cálculo.
- Impuestos (directo e indirecto).
    
    
    
    
    
    